import { createContext, useContext, useState } from 'react';
import PropTypes from 'prop-types';

const LanguageContext = createContext();

const translations = {
  en: {
    home: 'Home',
    services: 'Services',
    fleet: 'Fleet',
    specialOffers: 'Special Offers',
    contact: 'Contact',
    login: 'Login',
    register: 'Register',
    createAccount: 'Create Account',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    password: 'Password',
    optional: 'Optional',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    myBookings: 'My Bookings',
    newBooking: 'New Booking',
    noBookings: 'No bookings yet',
    cancel: 'Cancel',
    pending: 'Pending',
    confirmed: 'Confirmed',
    cancelled: 'Cancelled',
    completed: 'Completed',
    logout: 'Logout',
    welcome: 'Welcome',
    activeBookings: 'Active Bookings',
    totalTrips: 'Total Trips',
    totalSpent: 'Total Spent',
    currentBookings: 'Current Bookings',
    tripHistory: 'Trip History',
    invoices: 'Invoices',
    viewDetails: 'View Details',
    invoiceNumber: 'Invoice Number',
    date: 'Date',
    amount: 'Amount',
    actions: 'Actions',
    download: 'Download',
    hourlyHire: 'Hourly and full day hire',
    cityToCity: 'City-to-city rides',
    airportTransfers: 'Airport transfers',
    weddingChauffeur: 'Wedding Chauffeur',
    fashionWeek: 'Fashion Week Chauffeur',
    bookRide: 'Book a Ride',
    seConnecter: 'Sign in',
    connectToAccount: 'Connect to your account',
    personalizedExperience: 'Enjoy a 100% personalized experience!',
    needHelp: 'Need help?',
    myAccount: 'My Account',
    myAddresses: 'My Addresses',
    myReservations: 'My Reservations',
    dashboard: 'Dashboard',
    addNewAddress: 'Add New Address',
    addressName: 'Address Name (e.g. Home, Office)',
    street: 'Street Address',
    city: 'City',
    postalCode: 'Postal Code',
    country: 'Country',
    setAsDefault: 'Set as default address',
    default: 'Default',
    save: 'Save',
    editAddress: 'Edit Address',
    deleteAddress: 'Delete Address',
    defaultAddress: 'Default Address',
    completedTrips: 'Completed Trips',
    totalInvoices: 'Total Invoices',
    savedAddresses: 'Saved Addresses',
    oneWay: 'One Way',
    byHour: 'By the Hour',
    pickupLocation: 'Pick-up Location',
    dropoffLocation: 'Drop-off Location',
    enterPickupAddress: 'Enter pick-up address',
    enterDropoffAddress: 'Enter drop-off address',
    duration: 'Duration',
    hours: 'Hours',
    minutes: 'Minutes',
    hour: 'hour',
    hours_plural: 'hours',
    passenger: 'passenger',
    passengers: 'passengers',
    piece: 'piece',
    pieces: 'pieces',
  },
  fr: {
    home: 'Accueil',
    services: 'Services',
    fleet: 'Flotte',
    specialOffers: 'Offres Spéciales',
    contact: 'Contact',
    login: 'Connexion',
    register: 'Inscription',
    createAccount: 'Créer un compte',
    firstName: 'Prénom',
    lastName: 'Nom',
    email: 'Email',
    phone: 'Téléphone',
    password: 'Mot de passe',
    optional: 'Optionnel',
    alreadyHaveAccount: 'Vous avez déjà un compte ?',
    dontHaveAccount: "Vous n'avez pas de compte ?",
    myBookings: 'Mes Réservations',
    newBooking: 'Nouvelle Réservation',
    noBookings: 'Aucune réservation',
    cancel: 'Annuler',
    pending: 'En attente',
    confirmed: 'Confirmé',
    cancelled: 'Annulé',
    completed: 'Terminé',
    logout: 'Déconnexion',
    welcome: 'Bienvenue',
    activeBookings: 'Réservations Actives',
    totalTrips: 'Total des Voyages',
    totalSpent: 'Total Dépensé',
    currentBookings: 'Réservations Actuelles',
    tripHistory: 'Historique des Voyages',
    invoices: 'Factures',
    viewDetails: 'Voir les Détails',
    invoiceNumber: 'Numéro de Facture',
    date: 'Date',
    amount: 'Montant',
    actions: 'Actions',
    download: 'Télécharger',
    hourlyHire: 'Location à l\'heure et à la journée',
    cityToCity: 'Trajets inter-villes',
    airportTransfers: 'Transferts aéroport',
    weddingChauffeur: 'Chauffeur mariage',
    fashionWeek: 'Chauffeur Fashion Week',
    bookRide: 'Réserver',
    seConnecter: 'Se connecter',
    connectToAccount: 'Connectez-vous à votre compte',
    personalizedExperience: 'Bénéficiez d\'une expérience 100% personnalisée !',
    needHelp: 'Besoin d\'aide ?',
    myAccount: 'Mon compte',
    myAddresses: 'Mes adresses',
    myReservations: 'Mes réservations',
    dashboard: 'Tableau de bord',
    addNewAddress: 'Ajouter une adresse',
    addressName: 'Nom de l\'adresse (ex: Maison, Bureau)',
    street: 'Adresse',
    city: 'Ville',
    postalCode: 'Code postal',
    country: 'Pays',
    setAsDefault: 'Définir comme adresse par défaut',
    default: 'Par défaut',
    save: 'Enregistrer',
    editAddress: 'Modifier l\'adresse',
    deleteAddress: 'Supprimer l\'adresse',
    defaultAddress: 'Adresse par défaut',
    completedTrips: 'Voyages terminés',
    totalInvoices: 'Total des factures',
    savedAddresses: 'Adresses enregistrées',
    oneWay: 'Aller simple',
    byHour: 'À l\'heure',
    pickupLocation: 'Lieu de prise en charge',
    dropoffLocation: 'Lieu de dépose',
    enterPickupAddress: 'Entrez l\'adresse de prise en charge',
    enterDropoffAddress: 'Entrez l\'adresse de dépose',
    duration: 'Durée',
    hours: 'Heures',
    minutes: 'Minutes',
    hour: 'heure',
    hours_plural: 'heures',
    passenger: 'passager',
    passengers: 'passagers',
    piece: 'bagage',
    pieces: 'bagages',
  },
  ru: {
    home: 'Главная',
    services: 'Услуги',
    fleet: 'Автопарк',
    specialOffers: 'Специальные предложения',
    contact: 'Контакты',
    login: 'Войти',
    register: 'Регистрация',
    createAccount: 'Создать аккаунт',
    firstName: 'Имя',
    lastName: 'Фамилия',
    email: 'Email',
    phone: 'Телефон',
    password: 'Пароль',
    optional: 'Необязательно',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    dontHaveAccount: 'Нет аккаунта?',
    myBookings: 'Мои бронирования',
    newBooking: 'Новое бронирование',
    noBookings: 'Нет бронирований',
    cancel: 'Отмена',
    pending: 'В ожидании',
    confirmed: 'Подтверждено',
    cancelled: 'Отменено',
    completed: 'Завершено',
    logout: 'Выйти',
    welcome: 'Добро пожаловать',
    activeBookings: 'Активные Бронирования',
    totalTrips: 'Всего Поездок',
    totalSpent: 'Всего Потрачено',
    currentBookings: 'Текущие Бронирования',
    tripHistory: 'История Поездок',
    invoices: 'Счета',
    viewDetails: 'Подробнее',
    invoiceNumber: 'Номер Счёта',
    date: 'Дата',
    amount: 'Сумма',
    actions: 'Действия',
    download: 'Скачать',
    hourlyHire: 'Почасовая и дневная аренда',
    cityToCity: 'Междугородние поездки',
    airportTransfers: 'Трансфер в аэропорт',
    weddingChauffeur: 'Свадебный шофер',
    fashionWeek: 'Шофер на Неделю моды',
    bookRide: 'Заказать поездку',
    seConnecter: 'Войти',
    connectToAccount: 'Войдите в свой аккаунт',
    personalizedExperience: 'Получите 100% персонализированный опыт!',
    needHelp: 'Нужна помощь?',
    myAccount: 'Мой аккаунт',
    myAddresses: 'Мои адреса',
    myReservations: 'Мои бронирования',
    dashboard: 'Панель управления',
    addNewAddress: 'Добавить новый адрес',
    addressName: 'Название адреса (например, Дом, Офис)',
    street: 'Улица',
    city: 'Город',
    postalCode: 'Почтовый индекс',
    country: 'Страна',
    setAsDefault: 'Сделать адресом по умолчанию',
    default: 'По умолчанию',
    save: 'Сохранить',
    editAddress: 'Редактировать адрес',
    deleteAddress: 'Удалить адрес',
    defaultAddress: 'Адрес по умолчанию',
    completedTrips: 'Завершенные поездки',
    totalInvoices: 'Всего счетов',
    savedAddresses: 'Сохраненные адреса',
    oneWay: 'В одну сторону',
    byHour: 'Почасовая',
    pickupLocation: 'Место посадки',
    dropoffLocation: 'Место высадки',
    enterPickupAddress: 'Введите адрес посадки',
    enterDropoffAddress: 'Введите адрес высадки',
    duration: 'Длительность',
    hours: 'Часы',
    minutes: 'Минуты',
    hour: 'час',
    hours_plural: 'часов',
    passenger: 'пассажир',
    passengers: 'пассажиров',
    piece: 'место',
    pieces: 'мест',
  },
  es: {
    home: 'Inicio',
    services: 'Servicios',
    fleet: 'Flota',
    specialOffers: 'Ofertas Especiales',
    contact: 'Contacto',
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    createAccount: 'Crear Cuenta',
    firstName: 'Nombre',
    lastName: 'Apellido',
    email: 'Email',
    phone: 'Teléfono',
    password: 'Contraseña',
    optional: 'Opcional',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    dontHaveAccount: '¿No tienes una cuenta?',
    myBookings: 'Mis Reservas',
    newBooking: 'Nueva Reserva',
    noBookings: 'No hay reservas',
    cancel: 'Cancelar',
    pending: 'Pendiente',
    confirmed: 'Confirmado',
    cancelled: 'Cancelado',
    completed: 'Completado',
    logout: 'Cerrar sesión',
    welcome: 'Bienvenido',
    activeBookings: 'Reservas Activas',
    totalTrips: 'Total de Viajes',
    totalSpent: 'Total Gastado',
    currentBookings: 'Reservas Actuales',
    tripHistory: 'Historial de Viajes',
    invoices: 'Facturas',
    viewDetails: 'Ver Detalles',
    invoiceNumber: 'Número de Factura',
    date: 'Fecha',
    amount: 'Importe',
    actions: 'Acciones',
    download: 'Descargar',
    hourlyHire: 'Alquiler por hora y día completo',
    cityToCity: 'Viajes entre ciudades',
    airportTransfers: 'Traslados al aeropuerto',
    weddingChauffeur: 'Chófer de bodas',
    fashionWeek: 'Chófer Semana de la Moda',
    bookRide: 'Reservar viaje',
    seConnecter: 'Iniciar sesión',
    connectToAccount: 'Conecta a tu cuenta',
    personalizedExperience: '¡Disfruta de una experiencia 100% personalizada!',
    needHelp: '¿Necesitas ayuda?',
    myAccount: 'Mi cuenta',
    myAddresses: 'Mis direcciones',
    myReservations: 'Mis reservas',
    dashboard: 'Panel de control',
    addNewAddress: 'Añadir nueva dirección',
    addressName: 'Nombre de la dirección (ej. Casa, Oficina)',
    street: 'Calle',
    city: 'Ciudad',
    postalCode: 'Código postal',
    country: 'País',
    setAsDefault: 'Establecer como dirección predeterminada',
    default: 'Predeterminada',
    save: 'Guardar',
    editAddress: 'Editar dirección',
    deleteAddress: 'Eliminar dirección',
    defaultAddress: 'Dirección predeterminada',
    completedTrips: 'Viajes completados',
    totalInvoices: 'Total de facturas',
    savedAddresses: 'Direcciones guardadas',
    oneWay: 'Un sentido',
    byHour: 'Por hora',
    pickupLocation: 'Lugar de recogida',
    dropoffLocation: 'Lugar de destino',
    enterPickupAddress: 'Ingrese la dirección de recogida',
    enterDropoffAddress: 'Ingrese la dirección de destino',
    duration: 'Duración',
    hours: 'Horas',
    minutes: 'Minutos',
    hour: 'hora',
    hours_plural: 'horas',
    passenger: 'pasajero',
    passengers: 'pasajeros',
    piece: 'pieza',
    pieces: 'piezas',
  },
  de: {
    home: 'Startseite',
    services: 'Dienstleistungen',
    fleet: 'Flotte',
    specialOffers: 'Sonderangebote',
    contact: 'Kontakt',
    login: 'Anmelden',
    register: 'Registrieren',
    createAccount: 'Konto erstellen',
    firstName: 'Vorname',
    lastName: 'Nachname',
    email: 'Email',
    phone: 'Telefon',
    password: 'Passwort',
    optional: 'Optional',
    alreadyHaveAccount: 'Sie haben bereits ein Konto?',
    dontHaveAccount: 'Sie haben noch kein Konto?',
    myBookings: 'Meine Buchungen',
    newBooking: 'Neue Buchung',
    noBookings: 'Keine Buchungen',
    cancel: 'Abbrechen',
    pending: 'Ausstehend',
    confirmed: 'Bestätigt',
    cancelled: 'Storniert',
    completed: 'Abgeschlossen',
    logout: 'Abmelden',
    welcome: 'Willkommen',
    activeBookings: 'Aktive Buchungen',
    totalTrips: 'Gesamte Fahrten',
    totalSpent: 'Gesamtausgaben',
    currentBookings: 'Aktuelle Buchungen',
    tripHistory: 'Fahrtverlauf',
    invoices: 'Rechnungen',
    viewDetails: 'Details Anzeigen',
    invoiceNumber: 'Rechnungsnummer',
    date: 'Datum',
    amount: 'Betrag',
    actions: 'Aktionen',
    download: 'Herunterladen',
    hourlyHire: 'Stunden- und Tagesmiete',
    cityToCity: 'Städteverbindungen',
    airportTransfers: 'Flughafentransfers',
    weddingChauffeur: 'Hochzeitschauffeur',
    fashionWeek: 'Fashion Week Chauffeur',
    bookRide: 'Fahrt buchen',
    seConnecter: 'Anmelden',
    connectToAccount: 'Mit Ihrem Konto verbinden',
    personalizedExperience: 'Genießen Sie ein 100% personalisiertes Erlebnis!',
    needHelp: 'Brauchen Sie Hilfe?',
    myAccount: 'Mein Konto',
    myAddresses: 'Meine Adressen',
    myReservations: 'Meine Reservierungen',
    dashboard: 'Dashboard',
    addNewAddress: 'Neue Adresse hinzufügen',
    addressName: 'Adressname (z.B. Zuhause, Büro)',
    street: 'Straße',
    city: 'Stadt',
    postalCode: 'Postleitzahl',
    country: 'Land',
    setAsDefault: 'Als Standardadresse festlegen',
    default: 'Standard',
    save: 'Speichern',
    editAddress: 'Adresse bearbeiten',
    deleteAddress: 'Adresse löschen',
    defaultAddress: 'Standardadresse',
    completedTrips: 'Abgeschlossene Fahrten',
    totalInvoices: 'Gesamtrechnungen',
    savedAddresses: 'Gespeicherte Adressen',
    oneWay: 'Einfache Fahrt',
    byHour: 'Nach Stunden',
    pickupLocation: 'Abholort',
    dropoffLocation: 'Zielort',
    enterPickupAddress: 'Geben Sie den Abholort ein',
    enterDropoffAddress: 'Geben Sie den Zielort ein',
    duration: 'Dauer',
    hours: 'Stunden',
    minutes: 'Minuten',
    hour: 'Stunde',
    hours_plural: 'Stunden',
    passenger: 'Passagier',
    passengers: 'Passagiere',
    piece: 'Gepäckstück',
    pieces: 'Gepäckstücke',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

LanguageProvider.propTypes = {
  children: PropTypes.node.isRequired
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 